robotiq_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: &loop_hz 50

# Effort Controllers
robotiq_2f_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &robot_joints
     - finger_joint
  constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.05
      finger_joint: {trajectory: 0.05, goal: 0.05}
  stop_trajectory_duration: 0.1
  state_publish_rate:  *loop_hz
  action_monitor_rate: 50
  gains: # Required because we're controlling an effort interface
    finger_joint: {p: 10,  d: 0.5, i: 0, i_clamp: 0}
