stages:
  - .pre
  - lint
  - build

variables:
  APT_CACHE_DIR: $CI_PROJECT_DIR/.cache/apt
  CATKIN_DIR: $CI_PROJECT_DIR/catkin
  SECOND_REPO_PATH: https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins

default:
  image: docker.zal.aero/zal/topics/docker/ros:noetic-ros-base
  retry:
    max: 1
    when: always
  cache:
    paths:
      - .cache/
      - catkin/
  before_script:
    - rm -f /etc/apt/apt.conf.d/docker-clean
    - echo -e "APT::Archives::MaxAge "'"7"'";\nAPT::Archives::MinAge "'"2"'";\nAPT::Archives::MaxSize "'"2000"'";\nDir::Cache::Archives "'"'"$APT_CACHE_DIR"'"'";" >> /etc/apt/apt.conf.d/20archive
    - dpkg --force-all -i $APT_CACHE_DIR/*.deb
    - apt-get install -f

install dependencies:
  stage: .pre
  before_script:
    - rm -f /etc/apt/apt.conf.d/docker-clean
    - echo -e "APT::Archives::MaxAge "'"7"'";\nAPT::Archives::MinAge "'"2"'";\nAPT::Archives::MaxSize "'"2000"'";\nDir::Cache::Archives "'"'"$APT_CACHE_DIR"'"'";" >> /etc/apt/apt.conf.d/20archive
    - shopt -s extglob
    - rm -rf catkin
    - mkdir -p $CATKIN_DIR/src && mv !(catkin|apt) $CATKIN_DIR/src
    - git clone $SECOND_REPO_PATH
    - mkdir -p $APT_CACHE_DIR ; mv /var/cache/apt/archives/* $APT_CACHE_DIR -f
    - apt-get update
    - apt-get install -y catkin-lint
  script:
    - rosdep update
    - rosdep install --from-paths catkin/src --ignore-src -r -y

catkin lint:
  stage: lint
  allow_failure: true
  script:
    - catkin_lint -W2 catkin | tee catkin_lint.txt
  artifacts:
    name: catkin_lint
    when: always
    paths:
      - catkin_lint.txt
    expire_in: 1 week

catkin build:
  stage: build
  script:
    - catkin config --init --extend /opt/ros/noetic --workspace catkin
    - catkin build --summarize --no-status --force-color --workspace catkin
