# Joints limits

joint_limits:
  palm_bar:  # This is the only driven joint
    min_position: 0.0
    max_position: 0.81
    max_velocity: 0.5
    max_effort: 100.0

  palm_proximal_phalanx:
    min_position: 0.0
    max_position: 0.8757
    max_velocity: 0.5
    max_effort: 100.0

  bar_fingertip:
    min_position: -0.8757
    max_position: 0.0
    max_velocity: 0.5
    max_effort: 100.0
