# Physical parameters

inertia_parameters:
  palm:
    origin:
      xyz: 0.0 0.0 0.0
      rpy: 0.0 0.0 0.0
    mass: 1.3
    inertia:
      ixx: 0.006012
      ixy: 0.000079
      ixz: -0.00024
      iyy: 0.012892
      iyz: 0.0
      izz: 0.002435

  finger_link_0:
    origin:
      xyz: 0.0 0.0 0.0
      rpy: 0.0 0.0 0.0
    mass: 0.05
    inertia:
      ixx: 0.01
      ixy: -0.00002
      ixz: 0.00001
      iyy: 0.0008
      iyz: 0.0
      izz: 0.0001

  finger_link_1:
    origin:
      xyz: 0.0 0.0 0.0
      rpy: 0.0 0.0 0.0
    mass: 0.15
    inertia:
      ixx: 0.001859
      ixy: -0.000376
      ixz: 0.000028
      iyy: 0.012756
      iyz: 0.0
      izz: 0.0024

  finger_link_2:
    origin:
      xyz: 0.0 0.0 0.0
      rpy: 0.0 0.0 0.0
    mass: 0.15
    inertia:
      ixx: 0.001859
      ixy: -0.000376
      ixz: 0.000028
      iyy: 0.012756
      iyz: 0.0
      izz: 0.0024

  finger_link_3:
    origin:
      xyz: 0.0 0.0 0.0
      rpy: 0.0 0.0 0.0
    mass: 0.05
    inertia:
      ixx: 0.001239
      ixy: -0.000251
      ixz: 0.000019
      iyy: 0.00085
      iyz: 0.0
      izz: 0.001632

offsets:
  palm_finger_1_joint:
    origin:
      xyz: -0.0455 0.0214 0.036
      rpy: 0.0 3.1416 -1.57

  palm_finger_2_joint:
    origin:
      xyz: -0.0455 0.0214 -0.036
      rpy: 0.0 3.1416 -1.57

  palm_finger_middle_joint:
    origin:
      xyz: 0.0455 0.0214 0.0
      rpy: 0.0 0.0 1.57

  link_0:
    origin:
      xyz: 0.020 0.0 0.0
      rpy: 0.0 0.0 0.0

  link_1:
    origin:
      xyz: 0.050 -0.028 0.0
      rpy: 0.0 0.0 -0.52

  link_2:
    origin:
      xyz: 0.039 0.0 0.0075
      rpy: 0.0 0.0 0.0

  link_3:
    origin:
      xyz: 0.0 0.0 0.0
      rpy: 0.0 0.0 0.52

  joint_1:
    origin:
      xyz: 0.020 0.0 0.0
      rpy: 0.0 0.0 0.0

  joint_2:
    origin:
      xyz: 0.050 -0.028 0.0
      rpy: 0.0 0.0 -0.52

  joint_3:
    origin:
      xyz: 0.039 0.0 0.0
      rpy: 0.0 0.0 0.0
