joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: &loop_hz 500

robotiq_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: &robot_joints
     - finger_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      finger_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  *loop_hz
  action_monitor_rate: 10

robotiq_eff_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: *robot_joints
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      finger_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  *loop_hz
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    finger_joint: {p: 200,  d: 0.1, i: 5.0, i_clamp: 0.2}

robotiq_joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints

robotiq_joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *robot_joints
